### ISSUE TITLE
Add SiteNow install profile into uiowa01

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa01#182]

**Comment by pyrello** [comment]
I added the postponed label to this because I'm not going to be able to undertake it right away. There are potentially significant hurdles to overcome in this process as we may have different dependencies and that will need to be resolved. Also, in switching to 8.8.x, I'm not sure if their Sitenow will just work with that, or there will need to be adjustments.

**Comment by pyrello** [comment]
In light of recent conversations, I decided to take a stab at this, just to get a sense of what the hurdles of it would be. Its a bit more complicated than just importing the sitenow profile, which is not entirely self-contained (and neither is collegiate_basic).

Here are the things I can tell so far that would need to be resolved:
* Add composer.json to sitenow and add its dependencies there.
* Add drupal/core patches from uiowa/uiowa to sitenow composer.json.
* Move custom module dependencies of sitenow from docroot/modules/custom to docroot/profiles/custom/sitenow/modules.
* Move uiowa_bootstrap theme into docroot/profiles/custom/sitenow/themes.
* Come up with a strategy for $config_directories[CONFIG_SYNC_DIRECTORY] setting, which is currently handled via global include.
* Resolve dependency issues between sitenow and collegiate_basic profiles - this actually wasn't an issue as far as I could tell so far. I didn't go so far as adding the sitenow patches yet, which could change things, but it mostly seemed to not be a problem for composer.

Who knows what else, beyond that. I didn't make it all the way through making these changes, so there are probably other issues I haven't thought of yet. This should be a good jumping off point for evaluating this option further.

**Comment by pyrello** [comment]
I was able to get a `drush si sitenow --existing-config` to work. I had to take the following steps to get it to work:

* `git checkout upstream/master -- docroot/profiles/custom/sitenow` - I have the `uiowa/uiowa` repo set up as the 'upstream' remote in my local git settings.
* `cd docroot/profiles/custom/sitenow && composer init` to create a composer.json file in the sitenow directory.
* Added all dependencies to the sitenow composer.json that were mentioned in an error message when first trying the `drush si` command. https://github.com/uiowa/uiowa/blob/master/composer.json#L43
* Added the patches from the `uiowa/uiowa` repo to the sitenow composer.json (as well as the required other settings for patching). https://github.com/uiowa/uiowa/blob/master/composer.json#L128
* Removed the following patch from the sitenow composer.json (fixed in 8.8.x): https://github.com/uiowa/uiowa/blob/master/composer.json#L151
* Added `$config_directories[CONFIG_SYNC_DIRECTORY] = DRUPAL_ROOT . '/profiles/custom/sitenow/config/sync';` to the end of the settings file for the site I was going to install. This is obviously not meant as a long term solution, just a quick workaround to get it working.
* `git checkout upstream/master -- docroot/modules/custom/.` to pull in the custom modules from uiowa/uiowa
* `git checkout upstream/master -- docroot/themes/custom/uiowa_bootstrap` to pull in the uiowa_bootstrap custom theme.

**Comment by pyrello** [comment]
Its interesting to look back at this considering where we ended up.
