### ISSUE TITLE
Move uiowa_lb_blocks breakpoints and image styles into collegiate_theme

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa01#224]
The responsive image styles and breakpoints are currently defined in the uiowa_lb_blocks when they should set in collegiate_theme.

**Comment by pyrello** [comment]
@bspeare We should probably talk about how this issue should intersect with #126. Specifically, there is going to be a set of responsive images - and I guess breakpoints as well - defined in the media_core module to handle embedding responsive images via CKEditor. Should we consolidate these down? Are there going to be additional responsive image styles defined that are only relevant to the uiowa_lb_blocks module?

**Comment by bspeare** [comment]
That is a good question.   I was also thinking with regards to #230, should we keep the image styles and breakpoints within uiowa_lb_blocks module to make it something that can be shared easier?

**Comment by pyrello** [comment]
I think the potential issue with putting image styles and breakpoints in uiowa_lb_blocks is that it would create a circular dependency with our media_core module, since the custom blocks depend on the media_image module. And media_core would then depend on uiowa_lb_blocks. Personally, I think we should put them in media_core, which could potentially be a starting point for a shared set of assets down the road.

**Comment by bspeare** [comment]
Should I revert these changes https://github.com/uiowa/uiowa01/pull/229/commits/b4a0d10b910726937d961fbc18a3ad97fc3bf111 for now?

**Comment by pyrello** [comment]
I might be a good idea. Sorry to keep changing my mind :|

**Comment by pyrello** [comment]
@bspeare Here is what I am thinking: We move the breakpoints to media_core and update uiowa_lb_blocks responsive image config to point to those breakpoints instead. I'm not sure about moving the image styles that are contained in uiowa_lb_blocks because those seem to be somewhat specific to the block implementations. We are still in the process of deciding what sets of image styles to use over at https://github.com/uiowa/uiowa01/issues/221#issuecomment-558177921, so maybe these will overlap or maybe they won't.

**Comment by pyrello** [comment]
I think we will close this for now and possibly revisit the issue as part of the broader effort to reorganize the various components in the profile.
